Chat.Web/Chat.Web/Components/SearchedFriendsViewComponent.cs
using Chat.Application.Services.UserServices.Interface;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Web.Components
{
    public class SearchedFriendsViewComponent 
        (IUserService UserService) : ViewComponent
    {
       
       // === Getting Data --> ReturnSearchedFriendsViewComponent Action (SearchController) --> Ajax (Search View)
        public async Task<IViewComponentResult> InvokeAsync(string username)
        {
            var friends = await UserService.ContainsUsernameAsync(username);
            return View("SearchedFriendsVC" , friends);
        }

    }
}

Chat.Web/Chat.Web/Controllers/SearchController.cs
using System.Security.Claims;
using Chat.Application.Services.FriendServices.Interface;
using Chat.Application.Services.UserServices.Interface;
using Chat.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Web.Controllers
{
    [Authorize]
    public class SearchController 
        (IFriendService FriendService, IUserService UserService) : Controller
    {

        #region Index
        // === Getting Data From User Page ===
        [HttpGet]
        public IActionResult Search(int userId)
        {
            TempData["UserId"] = userId;
            return View();
        }
        #endregion

        #region Add Friend
        // === Getting Data From Search Page ===       
        [HttpGet]
        public async Task<IActionResult> AddFriend(int friendId)
        {
            int userId = Convert.ToInt32(TempData["UserId"]);
            UserModel user = await UserService.GetByIdAsync(userId);
            if (user == null)
                return NotFound();

            if (await FriendService.FriendshipExistsAsync(userId, friendId))
            {
                return RedirectToAction("Index", "Home", new { username = user.Username });
            }

            await FriendService.CreateAsync(userId, friendId);
            await FriendService.SaveChangesAsync();

            return RedirectToAction("Index", "Home", new { username = user.Username });
        }
        #endregion

        #region ViewComponent
        // === Getting Data --> Ajax (Search View) ===
        [HttpPost]
        public IActionResult ReturnSearchedFriendsViewComponent(string data)
        {
            return ViewComponent("SearchedFriends", data);
        }
        #endregion

    }
}

Chat.Web/Chat.Web/Views/Search/Search.cshtml
@{
	ViewData["Title"] = "Search";
}

<div class="search-card">


	<form>
		<div class="search-bar MyBorder-LeftTop-RightTop">
			<a class="search-back-btn" onClick="history.go(-1); return false;"><i class="fa fa-chevron-left back-icon" aria-hidden="true"></i></a>
			<input id="Search-value" type="text" class="search-input" placeholder="Type your Friend Username Here" value="" oninput="SearchFriend()"/>
			<button type="button" class="search-btn" >
				<i class="fa fa-search "></i>
			</button>
		</div>
	</form>





	<section id="friend-html" class="discussions MyBorder-LeftButtom-RightButtom">

		@await Component.InvokeAsync("SearchedFriends")

	</section>


</div>







@*===Ajax===*@

@*Ajax For Searching Friends Username*@

@section Search
{
	<script type="text/javascript">		
		function SearchFriend(){
				$.ajax({
					type: "POST",
					url: '@Url.Action("ReturnSearchedFriendsViewComponent")',
					data: {data:$("#Search-value").val()},					
					dataType: "html",					
					success: function (html) {
						$("#friend-html").html(html);
					},
					error: function () {
						alert("Error while inserting data");
					}
				});
		}
	</script>
}