Chat.Web/Chat.Web/Components/FooterChatViewComponent.cs
using Chat.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Web.Components
{
    public class FooterChatViewComponent : ViewComponent
    {
        // === Getting Data --> Chat View --> Chat Action (ChatController) ===
        public IViewComponentResult Invoke(FriendModel friendship)
        {            
            return View("FooterChatVC" , friendship);
        }
    }
}

Chat.Web/Chat.Web/Components/HeaderChatViewComponent.cs
using Chat.Application.Services.UserServices.Interface;
using Chat.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Web.Components
{
    public class HeaderChatViewComponent 
        (IUserService UserService) : ViewComponent
    {

        // === Getting Data --> Chat Page --> Chat Action (ChatController) ===
        public async Task<IViewComponentResult> InvokeAsync(int friendId)
        {
            UserModel friend = await UserService.GetByIdAsync(friendId);
            return View("HeaderChatVC" , friend);
        }
    }
}

Chat.Web/Chat.Web/Components/MessageViewComponent.cs
using Chat.Application.Services.MessageServices.Interface;
using Chat.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Web.Components
{
    public class MessageViewComponent 
        (IMessageService MessageService) : ViewComponent
    {
        
        // === Getting Data --> ReturnMessageViewComponent Action (ChatController) --> Ajax (Chat View) ===
        public async Task<IViewComponentResult> InvokeAsync(FriendModel friendship)
        {
            var messages = await MessageService.GetByFriendshipAsync(friendship);             
            
            var result = messages.OrderBy(m => m.MessageDate).ToList();
            ViewData["MessageUserId"]= friendship.UserId; 
            return View("MessageVC", result);                       
        }
    }
}

Chat.Web/Chat.Web/Controllers/ChatController.cs
using System.Security.Claims;
using Chat.Application.Services.FriendServices.Interface;
using Chat.Application.Services.MessageServices.Interface;
using Chat.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Web.Controllers
{
    [Authorize]
    public class ChatController 
        (IFriendService FriendService, IMessageService MessageService) : Controller
    {

        #region Index
        // === Getting Data From User Page ===
        [HttpGet]
        public async Task<IActionResult> Chat(int userId, int friendId)
        {
            FriendModel friendship = await FriendService.GetByIdAsync(userId, friendId);
            if (friendship == null)
            {
                return NotFound();
            }
            return View(friendship);
        }
        #endregion

        #region Add Message
        // === Getting Data From Ajax in Chat cshtml ===
        // === Adding Messages ===
        [HttpPost]
        public async Task<string> AddMessageAction(MessageModel data)
        {
            if (data.MessageText == null || data.MessageText == " ")
            {
                return "";
            }
            await MessageService.CreateAsync(data);
            await MessageService.SaveChangesAsync();
            return "";
        }
        #endregion

        #region Delete Message
        public async Task DeleteMessage(int MessageId, int sender)
        {
            var claims = User.Claims.FirstOrDefault(m => m.Type == ClaimTypes.NameIdentifier);
            if (claims.Value == sender.ToString())
            {
                await MessageService.DeleteAsync(MessageId);
                await MessageService.SaveChangesAsync();
            }
            else
            {
                NotFound();
            }
        }
        #endregion

        #region ViewComponent
        // === Getting Data From Ajax in Chat cshtml === 
        // === Fetching Messages ===
        [HttpPost]
        public IActionResult ReturnMessageViewComponent(FriendModel data)
        {
            return ViewComponent("Message", data);
        }
        #endregion

    }
}

Chat.Web/Chat.Web/Views/Chat/Chat.cshtml
@model FriendModel
@{
	ViewData["Title"] = "Chat";
	Layout = "_MainLayout";
}



<div class="chat-card MyBorder-all">

	<section class="chat">

		@*Header*@
		@await Component.InvokeAsync("HeaderChat", Model.FreindId)



		@*Chat*@
		<div id="message-update" class="messages-chat">
			@await Component.InvokeAsync("Message", Model)
		</div>



		@*Footer*@
		@await Component.InvokeAsync("FooterChat", Model)


	</section>

</div>








@*===Ajax===*@

@section Chat
{

	@*Ajax to Show Messages*@
	<script type="text/javascript">
		var data = {
			FriendsRelationId: @Model.FriendsRelationId ,
			FreindId: @Model.FreindId ,
			UserId: @Model.UserId
		}
	</script>

	<script type="text/javascript">

		setInterval(GetMessages , 3000);
		function GetMessages() {
				$.ajax({
					type: "POST",
					url: '@Url.Action("ReturnMessageViewComponent")',
					data: {data},
					dataType: "html",
					success: function (html) {
						$("#message-update").html(html);
					},
					error: function () {
						alert("Error while inserting data");
					}
				});
		}
	</script>


	@*Ajax to Add Messages*@


	<script type="text/javascript">
		function AddMessage(){
				$.ajax({
					type: "POST",
					url: '@Url.Action("AddMessageAction")',
					data: {FriendsRelationId:$("#friendrelationId").val(),Receiver:$("#friendId").val(),Sender:$("#UserId").val(),MessageDate:$("#MessageCreate").val(),MessageText:$("#message-input").val()},
					dataType: "text",
					success: function (html) {
						$("#message-input").val(html);
					},
					error: function () {
						alert("Error while inserting data");
					}
				});
		}
	</script>


	@*Ajax to Delete Message*@


	<script type="text/javascript">
		function DeleteMessage(messageId ,sender){
			console.log(messageId);
				$.ajax({
					type: "GET",
					url: '/chat/DeleteMessage?MessageId=' + messageId + '&sender=' + sender,
					success: function () {
						alert("Message Deleted");
					},
					error: function () {
						alert("Error while inserting data");
					}
				});
		}
	</script>
}